// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Interpidians.Catalyst.Client.Web.Controllers
{
    public partial class ExamController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ExamController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Paper()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Paper);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Start()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Start);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SubmitAnswer()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SubmitAnswer);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SkipAnswer()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SkipAnswer);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult PauseExamTimer()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.PauseExamTimer);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ResumeExamTimer()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ResumeExamTimer);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult NavigateToQuestion()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NavigateToQuestion);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Result()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ExamController Actions { get { return MVC.Exam; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Exam";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Exam";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Paper = "Paper";
            public readonly string Start = "Start";
            public readonly string SubmitAnswer = "SubmitAnswer";
            public readonly string SkipAnswer = "SkipAnswer";
            public readonly string PauseExamTimer = "PauseExamTimer";
            public readonly string ResumeExamTimer = "ResumeExamTimer";
            public readonly string NavigateToQuestion = "NavigateToQuestion";
            public readonly string Result = "Result";
            public readonly string ExamSessionExpired = "ExamSessionExpired";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Paper = "Paper";
            public const string Start = "Start";
            public const string SubmitAnswer = "SubmitAnswer";
            public const string SkipAnswer = "SkipAnswer";
            public const string PauseExamTimer = "PauseExamTimer";
            public const string ResumeExamTimer = "ResumeExamTimer";
            public const string NavigateToQuestion = "NavigateToQuestion";
            public const string Result = "Result";
            public const string ExamSessionExpired = "ExamSessionExpired";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Paper s_params_Paper = new ActionParamsClass_Paper();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Paper PaperParams { get { return s_params_Paper; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Paper
        {
            public readonly string id = "id";
            public readonly string paperName = "paperName";
        }
        static readonly ActionParamsClass_Start s_params_Start = new ActionParamsClass_Start();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Start StartParams { get { return s_params_Start; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Start
        {
            public readonly string id = "id";
            public readonly string SrNo = "SrNo";
        }
        static readonly ActionParamsClass_SubmitAnswer s_params_SubmitAnswer = new ActionParamsClass_SubmitAnswer();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SubmitAnswer SubmitAnswerParams { get { return s_params_SubmitAnswer; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SubmitAnswer
        {
            public readonly string answer = "answer";
        }
        static readonly ActionParamsClass_SkipAnswer s_params_SkipAnswer = new ActionParamsClass_SkipAnswer();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SkipAnswer SkipAnswerParams { get { return s_params_SkipAnswer; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SkipAnswer
        {
            public readonly string answer = "answer";
        }
        static readonly ActionParamsClass_PauseExamTimer s_params_PauseExamTimer = new ActionParamsClass_PauseExamTimer();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PauseExamTimer PauseExamTimerParams { get { return s_params_PauseExamTimer; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PauseExamTimer
        {
            public readonly string examTimer = "examTimer";
        }
        static readonly ActionParamsClass_ResumeExamTimer s_params_ResumeExamTimer = new ActionParamsClass_ResumeExamTimer();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResumeExamTimer ResumeExamTimerParams { get { return s_params_ResumeExamTimer; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResumeExamTimer
        {
            public readonly string examTimer = "examTimer";
        }
        static readonly ActionParamsClass_NavigateToQuestion s_params_NavigateToQuestion = new ActionParamsClass_NavigateToQuestion();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NavigateToQuestion NavigateToQuestionParams { get { return s_params_NavigateToQuestion; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NavigateToQuestion
        {
            public readonly string examNavigator = "examNavigator";
        }
        static readonly ActionParamsClass_Result s_params_Result = new ActionParamsClass_Result();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Result ResultParams { get { return s_params_Result; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Result
        {
            public readonly string examTimer = "examTimer";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string ExamSessionExpired = "ExamSessionExpired";
                public readonly string Index = "Index";
                public readonly string Paper = "Paper";
                public readonly string Result = "Result";
                public readonly string Start = "Start";
            }
            public readonly string ExamSessionExpired = "~/Views/Exam/ExamSessionExpired.cshtml";
            public readonly string Index = "~/Views/Exam/Index.cshtml";
            public readonly string Paper = "~/Views/Exam/Paper.cshtml";
            public readonly string Result = "~/Views/Exam/Result.cshtml";
            public readonly string Start = "~/Views/Exam/Start.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ExamController : Interpidians.Catalyst.Client.Web.Controllers.ExamController
    {
        public T4MVC_ExamController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            IndexOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void PaperOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string paperName);

        [NonAction]
        public override System.Web.Mvc.ActionResult Paper(string id, string paperName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Paper);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "paperName", paperName);
            PaperOverride(callInfo, id, paperName);
            return callInfo;
        }

        [NonAction]
        partial void StartOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string SrNo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Start(string id, string SrNo)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Start);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "SrNo", SrNo);
            StartOverride(callInfo, id, SrNo);
            return callInfo;
        }

        [NonAction]
        partial void SubmitAnswerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Interpidians.Catalyst.Client.Web.ViewModels.AnswerToSubmitVM answer);

        [NonAction]
        public override System.Web.Mvc.ActionResult SubmitAnswer(Interpidians.Catalyst.Client.Web.ViewModels.AnswerToSubmitVM answer)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SubmitAnswer);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "answer", answer);
            SubmitAnswerOverride(callInfo, answer);
            return callInfo;
        }

        [NonAction]
        partial void SkipAnswerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Interpidians.Catalyst.Client.Web.ViewModels.AnswerToSubmitVM answer);

        [NonAction]
        public override System.Web.Mvc.ActionResult SkipAnswer(Interpidians.Catalyst.Client.Web.ViewModels.AnswerToSubmitVM answer)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SkipAnswer);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "answer", answer);
            SkipAnswerOverride(callInfo, answer);
            return callInfo;
        }

        [NonAction]
        partial void PauseExamTimerOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Interpidians.Catalyst.Client.Web.ViewModels.ExamTimerAndNavigatorVM examTimer);

        [NonAction]
        public override System.Web.Mvc.JsonResult PauseExamTimer(Interpidians.Catalyst.Client.Web.ViewModels.ExamTimerAndNavigatorVM examTimer)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.PauseExamTimer);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "examTimer", examTimer);
            PauseExamTimerOverride(callInfo, examTimer);
            return callInfo;
        }

        [NonAction]
        partial void ResumeExamTimerOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Interpidians.Catalyst.Client.Web.ViewModels.ExamTimerAndNavigatorVM examTimer);

        [NonAction]
        public override System.Web.Mvc.JsonResult ResumeExamTimer(Interpidians.Catalyst.Client.Web.ViewModels.ExamTimerAndNavigatorVM examTimer)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ResumeExamTimer);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "examTimer", examTimer);
            ResumeExamTimerOverride(callInfo, examTimer);
            return callInfo;
        }

        [NonAction]
        partial void NavigateToQuestionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Interpidians.Catalyst.Client.Web.ViewModels.ExamTimerAndNavigatorVM examNavigator);

        [NonAction]
        public override System.Web.Mvc.ActionResult NavigateToQuestion(Interpidians.Catalyst.Client.Web.ViewModels.ExamTimerAndNavigatorVM examNavigator)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NavigateToQuestion);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "examNavigator", examNavigator);
            NavigateToQuestionOverride(callInfo, examNavigator);
            return callInfo;
        }

        [NonAction]
        partial void ResultOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Interpidians.Catalyst.Client.Web.ViewModels.ExamTimerAndNavigatorVM examTimer);

        [NonAction]
        public override System.Web.Mvc.ActionResult Result(Interpidians.Catalyst.Client.Web.ViewModels.ExamTimerAndNavigatorVM examTimer)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Result);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "examTimer", examTimer);
            ResultOverride(callInfo, examTimer);
            return callInfo;
        }

        [NonAction]
        partial void ExamSessionExpiredOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExamSessionExpired()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExamSessionExpired);
            ExamSessionExpiredOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
